version: '2'
services:
  web:
       build:
               context: ./
               dockerfile: Dockerfile
       container_name: basic_php
       volumes:
          - ./:/var/www/html/ 
       ports:
         - 8008:80
